[application]
name = "per-man"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "per-man"

[web.resource]
style = ["main.css"]
script = []

# Dieser Teil hat gefehlt und den Fehler verursacht:
[web.resource.dev]
style = []
script = []

[bundle]
identifier = "com.perman.app"
publisher = "hatem"