[application]
name = "per-man"
asset_dir = "assets"

[web.app]
# HTML title tag content
title = "per-man"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = ["main.css"]

# Additional JavaScript files
script = []

[web.resource.dev]
# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "com.perman.app"
publisher = "hatem"