CREATE TABLE IF NOT EXISTS buchung (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    datum DATE NOT NULL,
    bezeichnung TEXT NOT NULL,
    betrag FLOAT NOT NULL,
    intervall TEXT NOT NULL,
    art TEXT NOT NULL
);

 CREATE TABLE IF NOT EXISTS periode (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    bezeichnung DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS typ (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    bezeichnung DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS benutzer (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    benutzername TEXT NOT NULL,
    email TEXT NOT NULL,
    passwort TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS abo (
    id TEXT PRIMARY KEY UNIQUE,
    bezeichnung TEXT NOT NULL,
    beginn DATE NOT NULL,
    dauer FLOAT NOT NULL,
    kuend_frist FLOAT NOT NULL
);